### ISSUE TITLE
License Info

### ISSUE THREAD

**Issue by masammut** [sjmelia/OAuth.Client#1]
OAuth.Client is listed as MIT licensed on nuget (https://www.nuget.org/packages/ArrayOfBytes.OAuth.Client) would you be able to add a license file to this github repo too please?

**Comment by sjmelia** [comment]
Hi masammut if you open a PR I can merge it, thanks.

**Comment by masammut** [comment]
Doing it now.

**Comment by masammut** [comment]
PR done

**Comment by masammut** [comment]
Thanks for committing the PR (and for making the library available), closing ticket.
